# Comandos iniciais de importação e conexão ao banco de dados.

In [6]:
import sqlite3
from sqlite3 import Error

connection = sqlite3.connect("pizza_app.sqlite")

# Função para executar uma QUERY

In [7]:
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)

        # commit necessário para alterações no banco
        connection.commit() ###

        print(f"Query executada.")
        if cursor.rowcount != -1:
            print(f"{cursor.rowcount} linha(s) afetadas")

    except Error as e:
        print(f"Erro: '{e}'")

# Função para executar uma QUERY DE LEITURA

In [8]:
def execute_read_query(connection, query):
    cursor = connection.cursor()
    result = None
    try:
        cursor.execute(query)
        result = cursor.fetchall()

        return result
    except Error as e:
        print(f"Erro: '{e}'")

*exemplo*

In [9]:
tabela = 'produto'
query = f"SELECT * FROM {tabela}"
resultado = execute_read_query(connection, query)

print(f"Tabela: {tabela}")
try:
    for res in resultado:
        print(res)
except TypeError:
    print("Não é possível iterar sobre valores nulos")

Erro: 'no such table: produto'
Tabela: produto
Não é possível iterar sobre valores nulos

# Criando as TABELAS

In [10]:
# Cria a tabela produto #
create_produto_table = \
"""CREATE TABLE produto (
    id_produto INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo VARCHAR(50),
    desc_item VARCHAR(100),
    vl_preco DECIMAL(10, 2)
);"""

execute_query(connection, create_produto_table)
#########################

# Cria a tabela pedido #
create_pedido_table = \
"""CREATE TABLE pedido (
    id_pedido INTEGER PRIMARY KEY AUTOINCREMENT,
    dt_pedido DATE,
    fl_ketchup BOOLEAN,
    desc_uf CHAR(2),
    txt_recado TEXT
);"""

execute_query(connection, create_pedido_table)
#########################

# Cria a tabela item_pedido #
create_item_pedido_table = \
"""CREATE TABLE item_pedido (
    id_pedido INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    PRIMARY KEY (id_pedido, id_produto),
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
);"""
execute_query(connection, create_item_pedido_table)
#########################

Query executada.
Query executada.
Query executada.

# INSERINDO valores nas tabelas

In [11]:
## Inserindo registros manualmente

# Inserindo produto #
insert_produto = \
"""INSERT INTO
produto (tipo, desc_item, vl_preco)
VALUES
('ingrediente', 'camarão', 6),
('massa', 'tradicional', 9.25),
('borda', 'tradicional', 0),
('queijo', 'muçarela', 4),
('bebida', 'refrigerante', 5);
"""
execute_query(connection, insert_produto)
######################

# Inserindo pedido
insert_pedido = \
"""INSERT INTO
pedido (dt_pedido, fl_ketchup, desc_uf, txt_recado)
VALUES
('2023-06-01', TRUE, 'MG', 'Capricha no queijo!');
"""
execute_query(connection, insert_pedido)
######################

Query executada.
5 linha(s) afetadas
Query executada.
1 linha(s) afetadas

*forma de automatizar alterações em grande volume*

In [12]:
# Inserindo item_pedido
itens = (
    {'id_pedido': 1, 'id_produto': 2, 'qtd': 1},
    {'id_pedido': 1, 'id_produto': 3, 'qtd': 1},
    {'id_pedido': 1, 'id_produto': 1, 'qtd': 1},
    {'id_pedido': 1, 'id_produto': 4, 'qtd': 2},
    {'id_pedido': 1, 'id_produto': 5, 'qtd': 3}
)

insert_item_pedido = \
"""INSERT INTO item_pedido (id_pedido, id_produto, quantidade)
VALUES(:id_pedido, :id_produto, :qtd);"""

cursor = connection.cursor()
cursor.executemany(insert_item_pedido, itens)
connection.commit() # necessário para inserções
cursor.close()

# Exemplos

## Query para ler o nome de todas as tabelas registradas no esquema

In [13]:
select_table_names = \
"SELECT name FROM sqlite_schema WHERE type='table';"
tables = execute_read_query(connection, select_table_names)
print(tables, '\n')

for table in tables:
    select_all = f"SELECT * FROM {table[0]}"
    res = execute_read_query(connection, select_all)
    print(f"{table[0]}: {res}")

[('produto',), ('sqlite_sequence',), ('pedido',), ('item_pedido',)]

produto: [(1, 'ingrediente', 'camarão', 6), (2, 'massa', 'tradicional', 9.25), (3, 'borda', 'tradicional', 0), (4, 'queijo', 'muçarela', 4), (5, 'bebida', 'refrigerante', 5)]
sqlite_sequence: [('produto', 5), ('pedido', 1)]
pedido: [(1, '2023-06-01', 1, 'MG', 'Capricha no queijo!')]
item_pedido: [(1, 2, 1), (1, 3, 1), (1, 1, 1), (1, 4, 2), (1, 5, 3)]

## Dropando

In [14]:
execute_query(connection, "DELETE FROM item_pedido;")
execute_query(connection, "DELETE FROM pedido;")
execute_query(connection, "DELETE FROM produto;")

Query executada.
5 linha(s) afetadas
Query executada.
1 linha(s) afetadas
Query executada.
5 linha(s) afetadas

# Usando o PANDAS

In [15]:
# Baixando a versão modificada dos dados do Pizza Query.
! wget https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/item_pedido.csv
! wget https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/pedido.csv
! wget https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/produto.csv

--2026-06-13 20:30:53--  https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/item_pedido.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 103557 (101K) [text/plain]
Saving to: ‘item_pedido.csv’

item_pedido.csv     100%[===================>] 101.13K  --.-KB/s    in 0.01s

2026-06-13 20:30:53 (10.2 MB/s) - ‘item_pedido.csv’ saved [103557/103557]

--2026-06-13 20:30:53--  https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/pedido.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48218 (47K) [text/plain]
Saving to: ‘pedido.csv’

pedido.csv          100%[===================>]  47.09K  --.-KB/s    in 0.007s

2026-06-13 20:30:53 (6.28 MB/s) - ‘pedido.csv’ saved [48218/48218]

--2026-06-13 20:30:53--  https://raw.githubusercontent.com/camilalaranjeira/python-intermediario/main/pizza_query/produto.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2456 (2.4K) [text/plain]
Saving to: ‘produto.csv’

produto.csv         100%[===================>]   2.40K  --.-KB/s    in 0s

2026-06-13 20:30:53 (37.2 MB/s) - ‘produto.csv’ saved [2456/2456]

In [16]:
import pandas as pd
df_pedido = pd.read_csv(f'pedido.csv')
display(df_pedido.head())

   id_pedido   dt_pedido fl_ketchup desc_uf                  txt_recado
0          0  2023-05-11        NaN      GO                         NaN
1          1  2023-05-11        NaN      PR  Aquela pizza perfeita! :-D
2          2  2023-05-11        NaN      SP            Muito obrigado!!
3          3  2023-05-11        NaN      SP                         NaN
4          4  2023-05-11        NaN      RS        Capricha no peperoni

In [17]:
cursor = connection.cursor()
cursor.execute(f"SELECT * FROM pedido WHERE id_pedido < 5;")
result = cursor.fetchall()

In [18]:
# df_pedido.to_sql('pedido', connection, if_exists='replace', index=False)
res = execute_read_query(connection, "SELECT sql FROM sqlite_schema")
for r in res:
    print(r[0])

CREATE TABLE produto (
    id_produto INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo VARCHAR(50),
    desc_item VARCHAR(100),
    vl_preco DECIMAL(10, 2)
)
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE pedido (
    id_pedido INTEGER PRIMARY KEY AUTOINCREMENT,
    dt_pedido DATE,
    fl_ketchup BOOLEAN,
    desc_uf CHAR(2),
    txt_recado TEXT
)
CREATE TABLE item_pedido (
    id_pedido INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    PRIMARY KEY (id_pedido, id_produto),
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
)
None

In [19]:
!pip install sqlmodel

Collecting sqlmodel
  Downloading sqlmodel-0.0.38-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: SQLAlchemy<2.1.0,>=2.0.14 in /usr/local/lib/python3.12/dist-packages (from sqlmodel) (2.0.50)
Requirement already satisfied: pydantic>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from sqlmodel) (2.12.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sqlmodel) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->sqlmodel) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->sqlmodel) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.0->sqlmodel) (0.4.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<2.1.0,>=2.0.14->sqlmodel) (3.5.1)
Downloading sqlmodel-0.0.38-py3-none-any.whl (27 kB)
Installing collected packages: sqlmodel
Successfully installed sqlmodel-0.0.38

In [20]:
from datetime import datetime
from sqlmodel import (
    SQLModel, Field, Relationship,
    create_engine, Session, select
)

## Definição de classes/tabelas
class Equipe(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    nome: str
    pessoas: list["Pessoa"] = Relationship(back_populates="equipe")

class Pessoa(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    nome: str
    apelido: str
    data_nasc: datetime

    id_equipe: int | None = Field(default=None, foreign_key="equipe.id")
    equipe: Equipe | None = Relationship(back_populates="pessoas")

# Iniciando a conexão com o banco (SQLite)
sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

# Criando as tabelas
SQLModel.metadata.create_all(engine)

# Inserindo dados (isso estaria em uma função)
with Session(engine) as session:
    pessoa1 = Pessoa(nome="André Augusto", apelido="Melhor amigo",
                      data_nasc=datetime(2007, 2, 8))
    pessoa2 = Pessoa(nome="Gabriel Felipe", apelido="Tilipe",
                      data_nasc=datetime(2005, 10, 19))

    session.add(pessoa1)
    session.add(pessoa2)
    session.commit()

# Fazendo consultas
with Session(engine) as session:
    statement = select(Pessoa).where(Pessoa.apelido == "Tilipe")
    pessoa = session.exec(statement).first()
    print(pessoa.id, pessoa.nome)

2026-06-13 20:31:05,569 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-06-13 20:31:05,574 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("equipe")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("equipe")

2026-06-13 20:31:05,578 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2026-06-13 20:31:05,583 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("equipe")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("equipe")

2026-06-13 20:31:05,588 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2026-06-13 20:31:05,592 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("pessoa")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("pessoa")

2026-06-13 20:31:05,597 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2026-06-13 20:31:05,600 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("pessoa")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("pessoa")

2026-06-13 20:31:05,605 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2026-06-13 20:31:05,609 INFO sqlalchemy.engine.Engine
CREATE TABLE equipe (
	id INTEGER NOT NULL,
	nome VARCHAR NOT NULL,
	PRIMARY KEY (id)
)

INFO:sqlalchemy.engine.Engine:
CREATE TABLE equipe (
	id INTEGER NOT NULL,
	nome VARCHAR NOT NULL,
	PRIMARY KEY (id)
)

2026-06-13 20:31:05,615 INFO sqlalchemy.engine.Engine [no key 0.00547s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00547s] ()

2026-06-13 20:31:05,640 INFO sqlalchemy.engine.Engine
CREATE TABLE pessoa (
	id INTEGER NOT NULL,
	nome VARCHAR NOT NULL,
	apelido VARCHAR NOT NULL,
	data_nasc DATETIME NOT NULL,
	id_equipe INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(id_equipe) REFERENCES equipe (id)
)

INFO:sqlalchemy.engine.Engine:
CREATE TABLE pessoa (
	id INTEGER NOT NULL,
	nome VARCHAR NOT NULL,
	apelido VARCHAR NOT NULL,
	data_nasc DATETIME NOT NULL,
	id_equipe INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(id_equipe) REFERENCES equipe (id)
)

2026-06-13 20:31:05,642 INFO sqlalchemy.engine.Engine [no key 0.00221s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00221s] ()

2026-06-13 20:31:05,669 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-06-13 20:31:05,686 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-06-13 20:31:05,698 INFO sqlalchemy.engine.Engine INSERT INTO pessoa (nome, apelido, data_nasc, id_equipe) VALUES (?, ?, ?, ?) RETURNING id

INFO:sqlalchemy.engine.Engine:INSERT INTO pessoa (nome, apelido, data_nasc, id_equipe) VALUES (?, ?, ?, ?) RETURNING id

2026-06-13 20:31:05,704 INFO sqlalchemy.engine.Engine [generated in 0.00027s (insertmanyvalues) 1/2 (ordered; batch not supported)] ('André Augusto', 'Melhor amigo', '2007-02-08 00:00:00.000000', None)

INFO:sqlalchemy.engine.Engine:[generated in 0.00027s (insertmanyvalues) 1/2 (ordered; batch not supported)] ('André Augusto', 'Melhor amigo', '2007-02-08 00:00:00.000000', None)

2026-06-13 20:31:05,708 INFO sqlalchemy.engine.Engine INSERT INTO pessoa (nome, apelido, data_nasc, id_equipe) VALUES (?, ?, ?, ?) RETURNING id

INFO:sqlalchemy.engine.Engine:INSERT INTO pessoa (nome, apelido, data_nasc, id_equipe) VALUES (?, ?, ?, ?) RETURNING id

2026-06-13 20:31:05,713 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/2 (ordered; batch not supported)] ('Gabriel Felipe', 'Tilipe', '2005-10-19 00:00:00.000000', None)

INFO:sqlalchemy.engine.Engine:[insertmanyvalues 2/2 (ordered; batch not supported)] ('Gabriel Felipe', 'Tilipe', '2005-10-19 00:00:00.000000', None)

2026-06-13 20:31:05,719 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

2026-06-13 20:31:05,738 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-06-13 20:31:05,750 INFO sqlalchemy.engine.Engine SELECT pessoa.id, pessoa.nome, pessoa.apelido, pessoa.data_nasc, pessoa.id_equipe
FROM pessoa
WHERE pessoa.apelido = ?

INFO:sqlalchemy.engine.Engine:SELECT pessoa.id, pessoa.nome, pessoa.apelido, pessoa.data_nasc, pessoa.id_equipe
FROM pessoa
WHERE pessoa.apelido = ?

2026-06-13 20:31:05,756 INFO sqlalchemy.engine.Engine [generated in 0.00624s] ('Tilipe',)

INFO:sqlalchemy.engine.Engine:[generated in 0.00624s] ('Tilipe',)

2 Gabriel Felipe
2026-06-13 20:31:05,765 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

In [21]:
df_pedido.to_sql('pedido', connection, if_exists='replace', index=False)
res = execute_read_query(connection, "SELECT sql FROM sqlite_schema")
for r in res:
    print(r[0])

CREATE TABLE produto (
    id_produto INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo VARCHAR(50),
    desc_item VARCHAR(100),
    vl_preco DECIMAL(10, 2)
)
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE item_pedido (
    id_pedido INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    PRIMARY KEY (id_pedido, id_produto),
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    FOREIGN KEY (id_produto) REFERENCES produto(id_produto)
)
None
CREATE TABLE "pedido" (
"id_pedido" INTEGER,
  "dt_pedido" TEXT,
  "fl_ketchup" INTEGER,
  "desc_uf" TEXT,
  "txt_recado" TEXT
)

In [22]:
query="""
SELECT desc_uf, COUNT(*) as count_pedidos
FROM pedido
GROUP BY desc_uf
ORDER BY count_pedidos DESC
LIMIT 5
"""
pd.read_sql_query(query, connection)

  desc_uf  count_pedidos
0      SP            395
1      RJ            103
2      MG             92
3      PR             76
4      RS             50